apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech/architecture/ticketing/auth
  template:
    metadata:
      labels:
        app: tech/architecture/ticketing/auth
    spec:
      containers:
        - name: auth
          image: 510033969879.dkr.ecr.us-east-2.amazonaws.com/tech/architecture/ticketing/auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: tech/architecture/ticketing/auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
